### ISSUE TITLE
Send attachments

### ISSUE THREAD

**Issue by wenjunche** [gautamsi/ews-javascript-api#11]
Hello

is sending file attachment supported yet?

Also, my company is looking into extending OWA.  I am wondering if you are interested in working together.  If you are, please contact me at wenjun@openfin.co

Thanks

**Comment by gautamsi** [comment]
Attachments are not available yet. 
I can spend some time in next few days to add Attachment features, stay tuned.

**Comment by gautamsi** [comment]
getting there, able to create Attachment and send it, loading items with InternetHeaders are an issue. next checkin should have GetAttachment and InternetHeaders reading fixed.

**Comment by gautamsi** [comment]
you should now be able to send attachment.  fetch 0.2.0 version from npm. 
 #13  contains attachment updates. 

completed:
send attachment with EmailMessage
ExchangeService.GetAttachments to load attachment from server. 

pending:
CreateAttachment (explicit request) - EmailMessage can be sent with attachment.
DeleteAttachment - delete attachment on server. 

example send message with attachment. (File attachment is added as base64 content rather than file name or stream/buffer)
```ts
var exch = new ExchangeService(ExchangeVersion.Exchange2013);
exch.Credentials = new ExchangeCredentials(credentials.userName, credentials.password);
exch.Url = new Uri("https://outlook.office365.com/Ews/Exchange.asmx");
EwsLogging.DebugLogEnabled = true; // false to turnoff debugging. 

var msgattach = new EmailMessage(exch);
msgattach.Subject = "Dentist Appointment";
msgattach.Body = new MessageBody("The appointment is with Dr. Smith.");
msgattach.ToRecipients.Add("grouptest@mysupport.in")
var file = msgattach.Attachments.AddFileAttachment("filename to attach.txt", "c29tZSB0ZXh0");
/** AddFileAttachment parameters - 
 * filename (name of attachment as shown in outlook/owa not actual file from disk), 
 * base64 content of file (read file from disk and convert to base64 yourself)
 */
msgattach.Send().then(() => {
    console.log("------------");
}, (ei) => {
    console.log(ei.stack, ei.stack.split("\n"));
    console.log("------------");
});
```
