### ISSUE TITLE
Managing affinity and headers

### ISSUE THREAD

**Issue by emcho92** [gautamsi/ews-javascript-api#112]
When subscribing to pull/push notifications on Office, there is a need to manage affinity, to make sure that the getEvents request for the notifications always go to the correct mailbox. In order to do this I need to set two headers, X-AnchorMailbox and X-PreferServerAffinity. I can do this via the HttpHeaders. So I set the headers and issue a subscribeToPullNotifications request. Then, I should get back a subscription response from office, which I do, however it does not contain the X-BackendOverrideCookie or ExchangeCookie as it says [here](https://msdn.microsoft.com/en-us/library/office/dn458789%28v=exchg.150%29.aspx), per the MSDN documentation. Any ideas why?

**Comment by gautamsi** [comment]
part of code which captures `ResponseHeaders` is missing in port 😢 

will add this as todo.

**Comment by auk2** [comment]
Has this missing functionality regarding the capture of the response headers been fixed in the master branch of this repository yet?. Im asking because I can also not get the X-BackendOverrideCookie from an on premise Exchange 2016 or an Exchange 365 Online wave 15 version.
I have tried both the: SubscribeToGroupPushNotifications and
the SubscribeToPushNotifications methods in order to trigger Exchange to send the cookies. I have also made sure via fiddler that the correct headers are being sent out in the request:

-

**Comment by dnaustin** [comment]
I have come across this too and done a bit of digging into it.

[`SimpleServiceRequestBase.InternalExecute`](https://github.com/gautamsi/ews-javascript-api/blob/656cdaf13fced06e5adeadca06388e41025fc534/src/js/Core/Requests/SimpleServiceRequestBase.ts#L53) passes through a parsed JsObject to `SimpleServiceRequestBase.ReadResponsePrivate` which in turn passes it to [`ExchangeServiceBase.ProcessHttpResponseHeaders`](https://github.com/gautamsi/ews-javascript-api/blob/656cdaf13fced06e5adeadca06388e41025fc534/src/js/Core/ExchangeServiceBase.ts#L389) which returns early rather than process the object. Enabling `ExchangeServiceBase.SaveHttpResponseHeaders` and passing through the IEwsHttpWebResponse object as well as the parsed JsObject would allow the HttpResponseHeaders to be set.

@gautamsi Would you like me to code it up for you to take a look at?

**Comment by PhilHannent** [comment]
This will be fixed when 0.10 is released as the code has been written as part of #326
