### ISSUE TITLE
Authenticating with an oAuth token

### ISSUE THREAD

**Issue by amlwwalker** [gautamsi/ews-javascript-api#179]
I am using the graph API which is using an oAuth token on behalf of users, is it possible to use an oAuth token to validate this?
I'm writing in Nodejs and would like to act on behalf of our users.

Thanks
Alex

**Comment by gautamsi** [comment]
well, I was going to implement this, found out that code is already implemented. 

instead of using `ExchangeCredentials` object you should use `OAuthCredentials` (`ews.OAuthCredentials`). in constructor pass the `access_token` from Azure like this `service.Credentials = new ews.OAuthCredentials("access_token string");` it worked in my test.

When you receive error 401, it is the time to refresh the access token.

**Comment by gautamsi** [comment]
closing as no response on this, you can reopen this anyways.
