### ISSUE TITLE
 How to use the package in Ionic2?

### ISSUE THREAD

**Issue by ChirsChan** [gautamsi/ews-javascript-api#190]
Hello,thank for your contribution,but after I install the package in my Ionic2 project,there is an error "cannot find module 'dns'",I spent two days trying fix it, could anybody give me some guide?

**Comment by gautamsi** [comment]
I have started working on ionic, will try to fix it for you. 
basically it needs to be rebuilt, I have some working idea for making single files out of all the typescript file and then build the single js output. other approach would be to create some kind of environment like build where it would not ask dns module. XHR service needs to be written as well for ionic platform as this one heavily depends on nodejs

**Comment by andreafoorlan** [comment]
Hi all, i have the same problem.
I'm trying to use the package in Ionic3 and when webpack compiles, there is the same error "cannot find module 'dns'".
Any news about that? I hope to fix this because your package looks awesome and i wanna use it in my projects

**Comment by gautamsi** [comment]
looks like there were many requests for this. here it is then
try new module [`ews-js-api-browser`](https://github.com/gautamsi/ews-js-api-browser)

everything is same only the way it is packaged and the name of npm package is different.  you can use any code targeted for nodejs using `ews-javascript-api`. 

## caveats

* do not use `StreamingSubscription` feature, the browser based code is buggy, it keeps all streaming response in memory (all events) and emits when they are received as well as combines them at the end. If you really want to use `Streaming Subscription`, use it with 1 min timeout, large timeout may break the app due to memory issue if the mailbox has tons of changes going, for example mailbox migration using non-Exchange tools. 
* there is no AOT support, you will end up packaging 3mb file. uglify may break due to being large file. 

let me know what error you face. Most errors in this one may be due to wrong sequence when I merged  it to single file.

**Comment by prasanthmpr** [comment]
**anyone have tested this api on ionic?**

**Comment by gautamsi** [comment]
@prasanthmpr  I have not tested this with NTLM authentication if you are looking for that. I have tested few functions which are working as expected.

**Comment by gautamsi** [comment]
closing to keep issue list tidy. please re open if you need any help with this. you can create issue for any specific problem you face with ionic.
