### ISSUE TITLE
Support for React Native?

### ISSUE THREAD

**Issue by VikramK** [gautamsi/ews-javascript-api#213]
I was trying it on React native and it doesn't seem to work. Would be great if it supports that too.

**Comment by gautamsi** [comment]
can you get me minimal repo with react native and this library, did you try `ews-js-api-browser`? 

if React native does not use XMLHTTPRequest then you have to create a shim for this.

**Comment by VikramK** [comment]
I could nodeify all the modules and run the library but finally the function calls are throwing below error.
<img width="377" alt="screen shot 2017-11-17 at 9 24 15 am" src="https://user-images.githubusercontent.com/2529913/32928676-2cba56d0-cb79-11e7-9c47-9cd2b05a80d4.png">

Looks like this line is failing in fetch.js

**Comment by gautamsi** [comment]
do you get full node environment? if yes then you can use this library 9`ews-javascript-api`) otherwise I need to look at a sample repo.

**Comment by eugrdn** [comment]
Hello, @gautamsi. I'm tried to use both of the ews-api you wrote. And both of them are incompatible with the react-native environment. I also tried to shim some dependencies but this didn't help me. Please take a look of the this [sample](https://github.com/eugrdn/ews-sample) (with expo usage).
I hope you could take some time to resolve this, because I need to start a new project, and it would be terrible to work with common EWS XML api.

**Comment by gautamsi** [comment]
@eugrdn can you get me a repo with 2 commit, 1st commit with basic react-native working with running  instruction and 2nd commit with how you tried to use this library with react-native. i can try fix this for all.

**Comment by eugrdn** [comment]
@gautamsi I've updated the repo (as you asked), now it's a common react-native app. Further info about launch you could get [here](https://facebook.github.io/react-native/docs/getting-started.html) in "Building Projects with Native Code"

**Comment by gautamsi** [comment]
this is how I was able to work with this. I will fix it in next build or provide revised instruction:
add following lines to top of `ExchangeWebService.js` file in `ews-js-api-browser` node module
```js
"use strict"; // existing line
if (!global.DOMParser) {
    global.DOMParser = require('xmldom').DOMParser;
}
if (!global.atob || !global.btoa) {
    global.atob = require('base-64').decode;
    global.btoa = require('base-64').encode;
}
```

**Comment by eugrdn** [comment]
P.S. what do you think, how soon could you update version to 0.10?

**Comment by gautamsi** [comment]
it may take form few weeks to few months 😞

**Comment by XavegX367** [comment]
Is the source code of this still available? At the moment I am getting a error: The package at "node_modules/fetch/lib/fetch.js" attempted to import the Node standard library module "http". It failed because the native React runtime does niet include the Node standard library.

I am running React Native through Expo.

Am I actually able to call this in my React Native app itself or should I setup a Node server to handle this?
