### ISSUE TITLE
How to get contacts from Directory folder using ews-javascript-api?

### ISSUE THREAD

**Issue by piavgh** [gautamsi/ews-javascript-api#245]
Hi @gautamsi ,

I can get all contacts from Your Contacts folder successfully.

How can I get all contacts in that Directory folder from EWS?

![screenshot_1](https://user-images.githubusercontent.com/4060207/38304132-8a25bbae-3832-11e8-8ed0-d39f8aadd062.png)

I tried this code but it throws error:

> Exception: The distinguished folder name is unrecognized.

```
ews.EwsLogging.DebugLogEnabled = false;
let exch = new ews.ExchangeService(ews.ExchangeVersion.Exchange2013);

exch.Credentials = new ews.ExchangeCredentials("username", "password");

exch.Url = new ews.Uri("https://outlook.office365.com/Ews/Exchange.asmx");

exch.FindItems(
    [
        new ews.FolderId(ews.WellKnownFolderName.Directory) // Changed .Contacts to .Directory
    ],
    null,
    null,
    new ews.ItemView(10),
    null,
    ews.ServiceErrorHandling.ReturnErrors
).then(function (resp) {
    resp.Responses[0].Results.Items.forEach(function (item) {
        console.log(item.EmailAddresses.Entries.Values);
    });
}, function (ei) {
    console.log(ei.stack, ei.stack.split("\n"));
});
```

Thank you very much.

**Comment by vsmolovik** [comment]
I've got the same issue but in php-ews. The solution is to use ResolveName.

Hereby are details:
So, you can get a list of contacts based on your existing code: try to use AllContacts folder - query EWS in order to get a list of folders and set filter by Folder Display Name, for example.
Having Folder Id enables to get a full list of contacts but you can get not full set of contact data as they you get from Exchange Contact folder.
After that you can query all contacts in addition with ResolveName calls in order to force the system query Active Directory (Directory) and give you all required contact details.
In my case, when I query contact folder, I cannot get contacts:OfficeLocation but when I do the ResolveName, I get complete set of data including contacts:OfficeLocation.

It looks like that it happens in such a way as ResolveName query Active Directory and gives you more data than the contact folder.

Hope it gives you an idea how you can solve your problem.
