### ISSUE TITLE
Example on how to get results from FindItems

### ISSUE THREAD

**Issue by maccyber** [gautamsi/ews-javascript-api#26]
Hi, I'm trying to get elements via the method *FindItems* from the exchange server.
In particular i'm interested in getting tasks.

Example code:
https://gist.github.com/maccyber/517b9b72c6ae01ff7b5f18f01be89450

Gives me:
```
[TypeError: Cannot read property 'WriteAttributesToXml' of null]
```

The *GetUserAvailability* example works.

**Comment by gautamsi** [comment]
there is a bug which will be fixed in next minor release. 

you do not have to wait for this bug, just change line 494 like this
```
        //position 2 - viewQueryStringOrSearchFilter (line 493)
        if (argsLength >= 2) //(line 494) (change form == to >=)
```

Slight change needed to your code as well. do not use .Instance of any Schema, it is marked internal in original code but can not make internal in TypeScript. I have used jsdoc comment as @internal for each internal methods.
```
groupBy.GroupOn = ews.EmailMessageSchema.Subject 
groupBy.AggregateOn = ews.ItemSchema.DateTimeReceived
```

with these two changes, it should work properly.

**Comment by maccyber** [comment]
Thanks you @gautamsi ❤ It works.

Great job with the code btw.

**Comment by gautamsi** [comment]
0.2.5 published.
