### ISSUE TITLE
Does the API have any support for self signed certificates?

### ISSUE THREAD

**Issue by spr-coconnell** [gautamsi/ews-javascript-api#310]
The current solution when working with a self-signed cert is to set:
ConfigurationApi.SetXHROptions({rejectUnauthorized : false});

My understanding is that all this does is mask the underlying problem and just let you continue when you are unable to verify a cert.  This makes the system open to man-in-the-middle attacks.

Is there any support for self-signed certs so that we don't have to set that flag to 'false'?

**Comment by gautamsi** [comment]
well, self signed certificates are like that, you either configure the certificate to be trusted system wide and use correct name as per the certificate to avoid this step. 

All self signed certificates are like that - prone to man in middle attack. 

i added this option so that you don't have to do NODE_TLS_REJECT_UNAUTHORIZED=0 to make the entire app vulnerable, you can get away with only making only EWS portion vulnerable due to server/certificate constraint you have in the environment. This is usually used when you have in house app or test environment running without proper certificate. in a production environment, you either have commercial cert or internal enterprise root CA to issue trusted certificates to your devices.

**Comment by bladerunner2020** [comment]
Have the same question. I think settings NODE_EXTRA_CA_CERTS environment variable should have work but it doesn't...

**Comment by bladerunner2020** [comment]
!!! Got it working !!!

Added the following code:
```
(function(){
	if(!process.env.NODE_EXTRA_CA_CERTS) return;
	try{
		var extraca = require("fs").readFileSync(process.env.NODE_EXTRA_CA_CERTS);
	}catch(e){
		return;
	}
	
	var NativeSecureContext = process.binding('crypto').SecureContext;
	var oldaddRootCerts = NativeSecureContext.prototype.addRootCerts;
	NativeSecureContext.prototype.addRootCerts = function(){
		var ret = oldaddRootCerts.apply(this,arguments);
		this.addCACert(extraca);
		return ret;
	};
})();

```
