### ISSUE TITLE
 Too many concurrent connections opened., Cannot open mailbox..

### ISSUE THREAD

**Issue by bladerunner2020** [gautamsi/ews-javascript-api#357]
Encountered error " Too many concurrent connections opened., Cannot open mailbox...", when I tried to read meeting room calendars. I use the raw FindItems request:

```js
 folders = calendarIds.map((id) => new FolderId(WellKnownFolderName.Calendar, new Mailbox(id)));
exch.FindItems(folders, null, null, cv, null, null);
```.

Found out that it returns data for first 16 calendars only. For 17+ response has an error 127 (too many concurrent connections).

Any idea, why is it?

**Comment by kstankov** [comment]
Check the throtelling policy for EWS. Exchange has limit for how many requests you may issue per second.

⁣Best regards,
Kiril Stankov.​

**Comment by bladerunner2020** [comment]
> Check the throtelling policy for EWS. Exchange has limit for how many requests you may issue per second. ⁣Best regards, Kiril Stankov.​

@kstankov, thanks. I thought that if I put all mailboxes in the same request it would be done as one request... Seems that was a wrong assumption...

PS
Just divided the request into few - each 16 mailboxes. It works.

**Comment by kstankov** [comment]
Nice.

⁣Best regards,
Kiril Stankov.​

**Comment by gautamsi** [comment]
few things to note.

1. You are using internal method (no public overload uses array of folders), although it works as that is the one used internally
2. Exchange would consider each mailbox as 1 connection, so you pretty soon reach limit of the connection. 
3. if you split the request and wait for the first request before sending another, it works.
3. To be able to process 100s of mailboxes, you want to use **impersonation**. with impersonation the number of connection is still 1 (from app side) per mailbox and they are also counted towards that impersonated mailbox rather than the calling credential.

**Comment by kstankov** [comment]
But 4. requires some settings on the exchange server side, like setting impersonation account and giving permissions, which is not always available.

⁣Best regards,
Kiril Stankov.​

**Comment by gautamsi** [comment]
well that is what Microsoft recommends. you need to work with Exchange admins to get credentials or run unoptimised calls to EWS.
